# Generated by Django 5.1 on 2024-09-10 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_custom_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='custom_fields',
            new_name='Other_details',
        ),
    ]
