# Generated by Django 5.1 on 2024-09-10 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_custom_fields_contact_other_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
